---
embedding_size: 100
hidden_size: 100
learning_rate: 0.001
epoch_num: 50
sched_step_size: 100
sched_gamma: 0.1
max_seq_len: 200
max_vocab_size: 4000
nhead: 5
num_layers: 5
dim_feedforward: 1024
try_one_batch: True